#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '


# for kitty styling with Starship 

eval "$(starship init bash)"

# Zoxide setup 

eval "$(zoxide init bash)"


